title: "Terreira de MÃ£e Maria"
baseurl: "/tmm7f"
remote_theme: wowthemesnet/mediumish-theme-jekyll
description: "Fraternidade Sete Flechas"
search_placeholder: "Pesquisar no site..."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 8
paginate_path: /page:num/