title: "Terreira de Mãe Maria fraternidade Sete Flechas"
description: >-
  Espaço dedicado à divulgação da cultura, orações e pontos cantados da 
  Terreira de Mãe Maria fraternidade Sete Flechas.
baseurl: "/tmm7f"
url: "https://giulianocurtinaz.github.io"

# Jekyll Now Settings
# -------------------
# To enable Google Analytics, change the following value to your tracking ID
# google_analytics: UA-123456-7

# Your avatar will be displayed in the header. (Optional)
# avatar: 

# Footer Social Links
footer-links:
  # dribbble: 
  # email: terreira@itinformatica.com.br
  facebook: MaeMariaSeteFlechas 
  # flickr: 
  # github: 
  # instagram: 
  # linkedin: 
  # pinterest: 
  # rss: rss
  # twitter: 
  # stackoverflow: 
  youtube: channel/UCRxKGCSZ4UUJxlijM9zhbnA 
  # googleplus: 

# Navigation (Manual Order preserved from logic)
header_pages:
  - index.md
  - pages/calendario-2025.md
  - pages/missao.md
  - pages/links-e-livros.md
  - pages/raiz-ubirajara.md
  - pages/localizacao.md
  - pages/pontos-cantados.md
  - pages/pagina-dos-amigos-dirigentes.md
  - pages/oracoes-umbandistas.md

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Theme Settings
remote_theme: barryclark/jekyll-now
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme