title: "Terreira de MÃ£e Maria"

baseurl: "" # Keep empty for custom domain. Use /tmm7f only if building specifically for github.io/tmm7f without custom domain.
url: "https://www.maemariaseteflechas.com.br"

remote_theme: wowthemesnet/mediumish-theme-jekyll
description: ""
search_placeholder: "Pesquisar no site..."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 8
paginate_path: /page:num/

collections:
  pontos:
    output: true
    permalink: /pontos/:path/